name: SCRAP
channels:
 - bioconda
 - conda-forge
dependencies:
  - fastqc
  - multiqc
  - flash
  - cutadapt
  - blast
  - hisat2
  - samtools
  - bedtools
  - gatk4
  - sra-tools
  - viennarna
  - bowtie2
  - picard
  - flexbar
  - homer
  - khmer
